### ISSUE TITLE
Add flexibility to module resolution

### ISSUE THREAD

**Issue by lencioni** [trotzig/import-js#127]
Similar to #125, I am encountering some naming convention in tests where there are `mocks` directories scattered throughout with filenames that match components that they mock, but when imported, they are imported as `mockComponentName`. For instance, There might be a component at `app/assets/javascripts/something/MyComponent`, a test at `spec/javascripts/something/MyComponent_spec.jsx`, and a mock at `spec/javascripts/something/mocks/MyComponent.jsx`. In the spec, the mock is imported as `import mockMyComponent from './mocks/MyComponent';`. Sometimes these are imported from further away, such as `import mockMyComponent from '../../../something/mocks/MyComponent';`. I wonder if we can think of a good way to add a little configuration to help resolve these better. Perhaps, this could be the same solution as #125.

**Comment by trotzig** [comment]
This is similar to #125, but sort of the opposite. How about we have two configuration options:

```json
"ignorePathPrefixes": ["brigade", "react-addons"],
"ignoreVariablePrefixes": ["Mock"]
```

I think those would line up nicely together. 

Another option would be to allow a `cleanVariableName` option with a regexp specifying what part of a word you want to use for importing. Something like

```json
"cleanVariableName": "^(?:Mock)?(.*)"
```

We would then use match group 1 for the name used to look for modules. 

Though I think the first option is simpler.

**Comment by lencioni** [comment]
While I think that would work, it would be preferential if this was done in
a way that would prevent the mockComponent variable from matching on the
Component in addition to mock/Component.

**Comment by lencioni** [comment]
Perhaps we could just do this type of directory name as part of variable
name matching by default, in a similar way that we normalize dashes and
underscores?

**Comment by trotzig** [comment]
You mean matching the last path token too? Or hardcode "mock"?

**Comment by lencioni** [comment]
Matching path tokens in general, but we could start with last path and see
if that's good enough.

**Comment by trotzig** [comment]
I'm currently looking at this. I realized when writing tests that "last path token" was a bit too restrictive. I think we want something like this:

`fooBarBaz` matches `app/foo/bar/baz.js` as well as `app/foo_bar_baz/js`, but not `foo/app/bar/baz.js`.

**Comment by trotzig** [comment]
Oddly enough, we already seem to support that. I just tried adding these tests and they all pass:

```ruby

        context 'when the variable name matches last folder+filename' do
          let(:existing_files) { ['sko/bar/foo.jsx'] }
          let(:word) { 'barFoo' }
          let(:text) { 'barFoo' }

          it 'resolves the import' do
            expect(subject).to eq(<<-EOS.strip)
import barFoo from 'sko/bar/foo';

barFoo
            EOS
          end
        end

        context 'when the variable name matches a few folders + filename' do
          let(:existing_files) { ['sko/bar/foo/ta.jsx'] }
          let(:word) { 'BarFooTa' }
          let(:text) { 'BarFooTa' }

          it 'resolves the import' do
            expect(subject).to eq(<<-EOS.strip)
import BarFooTa from 'sko/bar/foo/ta';

BarFooTa
            EOS
          end
        end
```

**Comment by trotzig** [comment]
Oh, but wait. It's the plural "s" in "mocks" that's making this not work.

**Comment by lencioni** [comment]
What if we offered a way to configure mappings from variable names to path names? Something like:

```json
{
  "^mock": "./mocks/"
}
```

**Comment by trotzig** [comment]
Before I saw your comment, I started working on a change. Look at what I did above and see if it's okay!

**Comment by lencioni** [comment]
I considered suggesting that as well and it might be good enough. Maybe include a comment that captures this suggestion if it proves to not be good enough?

**Comment by lencioni** [comment]
Also, thanks for working on these issues so quickly! I've been pretty busy as you can probably imagine, so it is really great to continue to see progress on this project. I'll keep filing issues as I encounter them. :)

**Comment by trotzig** [comment]
No problem! I figured you'd be swamped. Keep filing issues, and I'll happily work on them when I find time to do so. 

I added a comment explaining the alternative solution you laid out above.

**Comment by lencioni** [comment]
I just tried out 0.3.1, and this doesn't seem to be working for my use case. I'm not sure why yet.

I have the following files

```
spec/javascripts/Thing_spec.jsx
spec/javascripts/mocks/Thing.jsx
```

In the spec file, I have a variable named `mockThing`. When I try to import it, instead of getting `import mockThing from './mocks/Thing';` I get a message "No JS module to import for `mockThing`".

**Comment by lencioni** [comment]
So, I just noticed that I still had my lookup paths specified as a workaround for another issue as 

```json
"lookup_paths": [
  "app/assets/javascripts"
],
```

and removing that made this actually work. Thanks again for your work on this!

**Comment by lencioni** [comment]
Unfortunately, removing that lookup paths configuration breaks resolution for this:

```
app/assets/javascripts/something/MyComponent.jsx
app/assets/javascripts/components/Something.jsx
```

and trying to import `Something` from inside `MyComponent.jsx`. It should generate `import Something from '../components/Something';` but it fails.

**Comment by trotzig** [comment]
Interesting. Can you see if you can create a repro case?

**Comment by trotzig** [comment]
I tried this test case in `js_module_spec.rb` and it works:

```ruby
        context 'when the lookup_path is the current directory' do
          let(:lookup_path) { '.' }

          it 'produces a correct relative path' do
            expect(subject.import_path).to eq('./foo')
          end

          context 'when the file to import is in a sibling folder' do
            let(:make_relative_to) { 'app/swib/bar.js' }

            it 'produces a correct relative path' do
              expect(subject.import_path).to eq('../lib/foo')
            end
          end
        end
```

Also, in the brigade repo, importing `app/assets/components/Icon/index.jsx` from `app/assets/components/Button.jsx` (after removing `lookup_paths` and adding `use_relative_paths`) produces the following import: `const Icon = require('../Icon');`. We need to figure out what's different in your setup.

**Comment by trotzig** [comment]
I pushed a commit that I want you to try out when you have some time. It drops the requirement of being in the same lookup_path when importing relatively.

**Comment by lencioni** [comment]
I checked out 13246a22a5caf5dff68956d79b03634d745f1073 and unfortunately the issue persists. I'll try to put together a repro case today.

**Comment by lencioni** [comment]
Here's the repro case: https://github.com/lencioni/import-js-repro-case

**Comment by lencioni** [comment]
Also, this is what I wrote in the commit message, in case you missed it:

```
Add import-js bug repro case

I am running into a problem with import-js that this reproduces.

  https://github.com/trotzig/import-js/issues/127#issuecomment-172371738

There are two variations of the lookup_paths configuration that you'll
want to try out along with running fix imports on the .jsx files in
order to see the full scope of the problem.

- Including only "app/assets/javascripts" in lookup_paths: this writes
  these imports correctly, but will not use relative paths when invoked
  outside of the app/assets/javascripts directory (e.g. in specs).

- Including only "." in lookup_paths or removing lookup_paths config
  entirely: this writes the first import in the file correctly on the
  first run but subsequent imports on the same run or any imports on
  subsequent runs fail.
```

**Comment by trotzig** [comment]
Great! I'll have a look at this when I have some time over. Regarding the subsequent import runs, I wonder if we should have something that tests those cases. This isn't the first time we've seen issues. I'd hate to duplicate every single test though...

**Comment by lencioni** [comment]
I think I'm getting close to tracking this down. It seems to be happening somewhere in `Importer#find_js_modules`. Specifically, running the find command and egrep command produces a result on the first run but nothing on the second run. I'm going to look into the possibility of it erroring out.

**Comment by trotzig** [comment]
Thanks for looking into it!

**Comment by lencioni** [comment]
Yeah, it's erroring the second time with "find: illegal option -- n" which is a bit perplexing because I can see the `find` command we are running is `find  -name "**.js*" -not -path "./node_modules/*"` and that is identical to the first time it is run. Any ideas?

**Comment by lencioni** [comment]
Hmm, actually when I run that on the command line I get the same error. There must be an invisible character somewhere on the second run.

**Comment by lencioni** [comment]
Oh, it's missing the path on the second run.

**Comment by lencioni** [comment]
Yeah `@config.get('lookup_paths')` gives `['.']` on the first run but `['']` on subsequent runs.

**Comment by trotzig** [comment]
oh, I bet there's a `.sub!` instead of a `.sub` somewhere (probably js_module.rb).
